name: Deploy to Azure Web App

on:
    push:
        branches:
            - main

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            # checkout the repo
            - name: 'Checkout Github Action'
              uses: actions/checkout@master

            - name: Setup Node 20.x
              uses: actions/setup-node@v4
              with:
                  node-version: '20.x'
            - name: 'Install Dependencies'
              run: |
                  npm install
            - name: 'Azure webapp deploy'
              uses: azure/webapps-deploy@v2
              with:
                  app-name: elearn-for-all
                  publish-profile: ${{ secrets.azureWebAppPublishProfile }}